name: Deploy MVM Mezoenergy

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy production to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./public_html/
          server-dir: /public_html/
